### ISSUE TITLE
Авторизація

### ISSUE THREAD

**Issue by Bohdan13** [TeamNum3/RealEstate#2]
Авторизація користувача

1. Окрема перевірка правильності юзернейма і паролю, вивід відповідного повідомлення про помилку
2. При успішній авторихації ввиводити відповідне сповіщення/ переходити на головну сторінку

**Comment by OksanaKo** [comment]
Функція або статичний клас(набір ф-й) або ще щось для перевірки унікальності логіна/паролю/пошти(запит з бази). Менше іфів
